### ISSUE TITLE
Could you do this with C++ aswell?

### ISSUE THREAD

**Issue by YungSamzy** [Valinwolf/cross-aes#2]

**Comment by Valinwolf** [comment]
C++ is, unfortunately, not among the 12 languages I know. I initially made this library for a project (since abandoned) that needed to run locally and via the web. I haven't worked on this library in a long time and it does have done issues, as noted by another GitHub user.

**Comment by YungSamzy** [comment]
Ok. I don't know C++ either but I wanted to integrate it into a project if you knew it. Thanks for responding so fast. Without this library I would've ben lost. Thanks so much!
